"""create all 22 base tables

Revision ID: 0d8e51ed6370
Revises: 
Create Date: 2026-09-01 13:12:09.862090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d8e51ed6370'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('dept_code', sa.String(length=32), nullable=False, comment='部门编码，如 RD / PUR'),
    sa.Column('dept_name', sa.String(length=64), nullable=False, comment='部门名称'),
    sa.Column('parent_id', mysql.BIGINT(unsigned=True), nullable=True, comment='上级部门，自引用'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='deptstatus'), server_default='ACTIVE', nullable=False, comment='状态'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Created at (UTC)'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Last updated at (UTC)'),
    # created_by / updated_by FK 指向 users（后置，见 upgrade() 末尾补建，
    # 避免 departments <-> users 循环外键导致的建表顺序问题）
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], name='fk_dept_parent'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('dept_code', name='uk_dept_code')
    )
    op.create_index('ix_dept_parent', 'departments', ['parent_id'], unique=False)
    op.create_index('ix_dept_status', 'departments', ['status'], unique=False)
    op.create_table('number_sequences',
    sa.Column('sequence_key', sa.String(length=32), nullable=False, comment='PR/PO/REC/TXN/MAT/SUP/WH'),
    sa.Column('sequence_date', sa.Date(), nullable=False, comment='按日重置用业务日期；全局递增固定 1970-01-01'),
    sa.Column('current_value', mysql.BIGINT(unsigned=True), server_default='0', nullable=False, comment='当前值'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_number_sequences')),
    sa.UniqueConstraint('sequence_key', 'sequence_date', name='uk_seq')
    )
    op.create_table('permissions',
    sa.Column('perm_code', sa.String(length=64), nullable=False, comment='如 pr:approve'),
    sa.Column('perm_name', sa.String(length=64), nullable=False, comment='权限名称'),
    sa.Column('module', sa.String(length=32), nullable=False, comment='模块分组，前端菜单渲染用'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('perm_code', name='uk_perm_code')
    )
    op.create_index('ix_perm_module', 'permissions', ['module'], unique=False)
    op.create_table('roles',
    sa.Column('role_code', sa.Enum('ADMIN', 'APPLICANT', 'DEPT_MANAGER', 'BUYER', 'WAREHOUSE', name='rolecode'), nullable=False, comment='ADMIN/APPLICANT/DEPT_MANAGER/BUYER/WAREHOUSE'),
    sa.Column('role_name', sa.String(length=64), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='1=系统内置不可删除'),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='activestatus'), server_default='ACTIVE', nullable=False, comment='状态'),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Created at (UTC)'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Last updated at (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('role_code', name='uk_role_code')
    )
    op.create_index('ix_role_status', 'roles', ['status'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False, comment='登录账号'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt 哈希，明文永不落库'),
    sa.Column('real_name', sa.String(length=64), nullable=False, comment='姓名'),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('department_id', mysql.BIGINT(unsigned=True), nullable=True, comment='所属部门'),
    sa.Column('role_id', mysql.BIGINT(unsigned=True), nullable=False, comment='角色（v1 单角色）'),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='userstatus'), server_default='ACTIVE', nullable=False),
    sa.Column('last_login_at', mysql.DATETIME(fsp=3), nullable=True, comment='最后登录时间'),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Created at (UTC)'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Last updated at (UTC)'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_users_created_by_users'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_user_dept', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_user_role', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_users_updated_by_users'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name='uk_user_username')
    )
    op.create_index('ix_user_dept', 'users', ['department_id'], unique=False)
    op.create_index('ix_user_role', 'users', ['role_id'], unique=False)
    op.create_index('ix_user_status', 'users', ['status'], unique=False)
    op.create_table('approval_records',
    sa.Column('document_type', sa.Enum('PURCHASE_REQUISITION', 'PURCHASE_ORDER', name='documenttype'), nullable=False),
    sa.Column('document_id', mysql.BIGINT(unsigned=True), nullable=False, comment='单据 ID（非 FK）'),
    sa.Column('step_no', mysql.SMALLINT(unsigned=True), server_default='1', nullable=False, comment='审批级别，v1 恒为 1'),
    sa.Column('step_name', sa.String(length=64), nullable=True, comment='步骤名，如 部门主管审批'),
    sa.Column('approver_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('action', sa.Enum('SUBMIT', 'APPROVE', 'REJECT', 'CANCEL', name='approvalaction'), nullable=False),
    sa.Column('result_status', sa.String(length=32), nullable=False, comment='动作执行后单据状态快照'),
    sa.Column('comment', sa.String(length=1000), nullable=True, comment='审批意见，驳回时必填'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name='fk_ar_approver', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_records'))
    )
    op.create_index('ix_ar_approver', 'approval_records', ['approver_id'], unique=False)
    op.create_index('ix_ar_doc', 'approval_records', ['document_type', 'document_id'], unique=False)
    op.create_index('ix_ar_time', 'approval_records', ['created_at'], unique=False)
    op.create_table('department_managers',
    sa.Column('dept_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='是否主主管'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], name='fk_deptmgr_dept', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_deptmgr_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department_managers')),
    sa.UniqueConstraint('dept_id', 'user_id', name='uk_deptmgr')
    )
    op.create_index('ix_deptmgr_user', 'department_managers', ['user_id'], unique=False)
    op.create_table('materials',
    sa.Column('material_code', sa.String(length=32), nullable=False, comment='MAT-000001'),
    sa.Column('material_name', sa.String(length=128), nullable=False, comment='物料名称'),
    sa.Column('category', sa.String(length=64), nullable=True, comment='分类（电子件/结构件/紧固件）'),
    sa.Column('specification', sa.String(length=128), nullable=True, comment='规格型号'),
    sa.Column('unit', sa.String(length=16), nullable=False, comment='计量单位（个/kg/m/套）'),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='activestatus'), server_default='ACTIVE', nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Created at (UTC)'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Last updated at (UTC)'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_materials_created_by_users'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_materials_updated_by_users'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials')),
    sa.UniqueConstraint('material_code', name='uk_mat_code')
    )
    op.create_index('ix_mat_name', 'materials', ['material_name'], unique=False)
    op.create_index('ix_mat_status', 'materials', ['status'], unique=False)
    op.create_table('operation_logs',
    sa.Column('operator_id', mysql.BIGINT(unsigned=True), nullable=True, comment='操作人（登录失败时可能为 NULL）'),
    sa.Column('username_snapshot', sa.String(length=64), nullable=True, comment='账号快照'),
    sa.Column('action', sa.Enum('LOGIN', 'LOGIN_FAILED', 'PR_SUBMIT', 'PR_APPROVE', 'PR_REJECT', 'PR_CANCEL', 'PO_CREATE', 'PO_CONFIRM', 'RECEIPT_POST', 'RECEIPT_REVERSE', 'PERMISSION_CHANGE', name='auditaction'), nullable=False),
    sa.Column('module', sa.String(length=32), nullable=False, comment='所属模块'),
    sa.Column('document_type', sa.String(length=32), nullable=True, comment='关联单据类型'),
    sa.Column('document_id', mysql.BIGINT(unsigned=True), nullable=True, comment='关联单据 ID'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='操作描述'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='支持 IPv6'),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True, comment='链路追踪 ID'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], name='fk_ol_operator', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_logs'))
    )
    op.create_index('ix_ol_action', 'operation_logs', ['action'], unique=False)
    op.create_index('ix_ol_doc', 'operation_logs', ['document_type', 'document_id'], unique=False)
    op.create_index('ix_ol_operator', 'operation_logs', ['operator_id'], unique=False)
    op.create_index('ix_ol_time', 'operation_logs', ['created_at'], unique=False)
    op.create_table('purchase_requisitions',
    sa.Column('pr_no', sa.String(length=32), nullable=False, comment='PR-20260901-0001'),
    sa.Column('applicant_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('department_id', mysql.BIGINT(unsigned=True), nullable=False, comment='申请部门（单据快照，不随调岗漂移）'),
    sa.Column('apply_date', sa.Date(), nullable=False, comment='申请日期'),
    sa.Column('reason', sa.String(length=500), nullable=True, comment='申请事由'),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'CONVERTED', name='prstatus'), server_default='DRAFT', nullable=False),
    sa.Column('total_estimated_amount', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False, comment='明细预估金额合计（服务端汇总）'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Created at (UTC)'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Last updated at (UTC)'),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], name='fk_pr_applicant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_pr_created_by_users'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_pr_dept', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_pr_updated_by_users'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_requisitions')),
    sa.UniqueConstraint('pr_no', name='uk_pr_no')
    )
    op.create_index('ix_pr_applicant', 'purchase_requisitions', ['applicant_id'], unique=False)
    op.create_index('ix_pr_date', 'purchase_requisitions', ['apply_date'], unique=False)
    op.create_index('ix_pr_dept', 'purchase_requisitions', ['department_id'], unique=False)
    op.create_index('ix_pr_status', 'purchase_requisitions', ['status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('permission_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='fk_rp_permission', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_rp_role', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uk_role_perm')
    )
    op.create_index('ix_roleperm_perm', 'role_permissions', ['permission_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('supplier_code', sa.String(length=32), nullable=False, comment='SUP-000001'),
    sa.Column('supplier_name', sa.String(length=128), nullable=False),
    sa.Column('contact_person', sa.String(length=64), nullable=True, comment='联系人'),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='activestatus'), server_default='ACTIVE', nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Created at (UTC)'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Last updated at (UTC)'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_suppliers_created_by_users'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_suppliers_updated_by_users'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('supplier_code', name='uk_sup_code')
    )
    op.create_index('ix_sup_name', 'suppliers', ['supplier_name'], unique=False)
    op.create_index('ix_sup_status', 'suppliers', ['status'], unique=False)
    op.create_table('warehouses',
    sa.Column('warehouse_code', sa.String(length=32), nullable=False, comment='WH-000001'),
    sa.Column('warehouse_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='activestatus'), server_default='ACTIVE', nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Created at (UTC)'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Last updated at (UTC)'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_warehouses_created_by_users'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_warehouses_updated_by_users'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('warehouse_code', name='uk_wh_code')
    )
    op.create_index('ix_wh_status', 'warehouses', ['status'], unique=False)
    op.create_table('inventory_balances',
    sa.Column('warehouse_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('material_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False, comment='账面数量（>= 0，Q8）'),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False, comment='账面总金额'),
    sa.Column('average_unit_cost', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False, comment='移动加权平均单价'),
    sa.Column('version', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='乐观锁版本号'),
    sa.Column('last_transaction_at', mysql.DATETIME(fsp=3), nullable=True, comment='最近变动时间'),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Created at (UTC)'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Last updated at (UTC)'),
    sa.CheckConstraint('average_unit_cost >= 0', name=op.f('ck_inventory_balances_ib_avg_nonneg')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_inventory_balances_ib_qty_nonneg')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_inventory_balances_ib_amount_nonneg')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='fk_ib_mat', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_ib_wh', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_balances')),
    sa.UniqueConstraint('warehouse_id', 'material_id', name='uk_ib')
    )
    op.create_index('ix_ib_mat', 'inventory_balances', ['material_id'], unique=False)
    op.create_table('inventory_policies',
    sa.Column('warehouse_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('material_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('safety_stock', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False, comment='安全库存'),
    sa.Column('min_stock', sa.Numeric(precision=18, scale=4), nullable=True, comment='最低库存'),
    sa.Column('max_stock', sa.Numeric(precision=18, scale=4), nullable=True, comment='最高库存'),
    sa.Column('reorder_point', sa.Numeric(precision=18, scale=4), nullable=True, comment='补货点'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Created at (UTC)'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Last updated at (UTC)'),
    sa.CheckConstraint('max_stock IS NULL OR max_stock >= 0', name=op.f('ck_inventory_policies_max_stock_nonneg')),
    sa.CheckConstraint('min_stock IS NULL OR min_stock >= 0', name=op.f('ck_inventory_policies_min_stock_nonneg')),
    sa.CheckConstraint('reorder_point IS NULL OR reorder_point >= 0', name=op.f('ck_inventory_policies_reorder_point_nonneg')),
    sa.CheckConstraint('safety_stock >= 0', name=op.f('ck_inventory_policies_safety_stock_nonneg')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='fk_invpol_mat', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_invpol_wh', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_policies')),
    sa.UniqueConstraint('warehouse_id', 'material_id', name='uk_invpol')
    )
    op.create_index('ix_invpol_mat', 'inventory_policies', ['material_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('txn_no', sa.String(length=32), nullable=False, comment='TXN-20260901-000001'),
    sa.Column('transaction_type', sa.Enum('PURCHASE_IN', 'PURCHASE_IN_REVERSAL', 'ADJUST_IN', 'ADJUST_OUT', 'PRODUCTION_OUT', 'PRODUCTION_IN', name='txntype'), nullable=False),
    sa.Column('warehouse_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('material_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='带符号：入库正、出库负'),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False, comment='计价单价'),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False, comment='计价金额（quantity * unit_cost，带符号）'),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=4), nullable=False, comment='流水后余额快照，审计用'),
    sa.Column('source_type', sa.Enum('PURCHASE_RECEIPT', 'PURCHASE_RECEIPT_REVERSAL', 'MANUAL_ADJUST', 'PRODUCTION_ISSUE', 'PRODUCTION_RECEIPT', name='txnsourcetype'), nullable=True, comment='来源单据类型'),
    sa.Column('source_id', mysql.BIGINT(unsigned=True), nullable=True, comment='来源单据 ID（非 FK）'),
    sa.Column('source_item_id', mysql.BIGINT(unsigned=True), nullable=True, comment='来源单据明细 ID'),
    sa.Column('reversed_transaction_id', mysql.BIGINT(unsigned=True), nullable=True, comment='Q6：指向被冲销的原始流水'),
    sa.Column('transaction_at', mysql.DATETIME(fsp=3), nullable=False, comment='业务发生时间'),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.CheckConstraint("(transaction_type IN ('PURCHASE_IN','ADJUST_IN','PRODUCTION_IN') AND quantity > 0) OR (transaction_type IN ('PURCHASE_IN_REVERSAL','ADJUST_OUT','PRODUCTION_OUT') AND quantity < 0)", name=op.f('ck_inventory_transactions_it_sign')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_inventory_transactions_it_cost_nonneg')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_it_created_by_users'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='fk_it_mat', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_transaction_id'], ['inventory_transactions.id'], name='fk_it_reversed'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_it_wh', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_transactions')),
    sa.UniqueConstraint('txn_no', name='uk_txn_no')
    )
    op.create_index('ix_it_mat', 'inventory_transactions', ['material_id'], unique=False)
    op.create_index('ix_it_reversed', 'inventory_transactions', ['reversed_transaction_id'], unique=False)
    op.create_index('ix_it_source', 'inventory_transactions', ['source_type', 'source_id'], unique=False)
    op.create_index('ix_it_time', 'inventory_transactions', ['transaction_at'], unique=False)
    op.create_index('ix_it_type', 'inventory_transactions', ['transaction_type'], unique=False)
    op.create_index('ix_it_wh_mat', 'inventory_transactions', ['warehouse_id', 'material_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('po_no', sa.String(length=32), nullable=False, comment='PO-20260901-0001'),
    sa.Column('supplier_id', mysql.BIGINT(unsigned=True), nullable=False, comment='供应商（必填）'),
    sa.Column('buyer_id', mysql.BIGINT(unsigned=True), nullable=False, comment='采购员'),
    sa.Column('order_date', sa.Date(), nullable=False, comment='订单日期'),
    sa.Column('expected_date', sa.Date(), nullable=True, comment='期望到货日期'),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', name='postatus'), server_default='DRAFT', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False, comment='明细金额合计（服务端汇总）'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('updated_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Created at (UTC)'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Last updated at (UTC)'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name='fk_po_buyer', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_po_created_by_users'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='fk_po_supplier', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='fk_po_updated_by_users'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('po_no', name='uk_po_no')
    )
    op.create_index('ix_po_buyer', 'purchase_orders', ['buyer_id'], unique=False)
    op.create_index('ix_po_date', 'purchase_orders', ['order_date'], unique=False)
    op.create_index('ix_po_status', 'purchase_orders', ['status'], unique=False)
    op.create_index('ix_po_supplier', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('purchase_requisition_items',
    sa.Column('pr_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False, comment='行号，单内唯一'),
    sa.Column('material_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='申请数量'),
    sa.Column('converted_quantity', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False, comment='已转 PO 数量（Q3）'),
    sa.Column('estimated_unit_price', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False, comment='预估单价，允许为 0（Q9）'),
    sa.Column('estimated_amount', sa.Numeric(precision=18, scale=4), sa.Computed('ROUND(requested_quantity * estimated_unit_price, 4)', persisted=True), nullable=False, comment='预估金额（生成列）'),
    sa.Column('required_date', sa.Date(), nullable=True, comment='需求日期'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Created at (UTC)'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Last updated at (UTC)'),
    sa.CheckConstraint('converted_quantity >= 0 AND converted_quantity <= requested_quantity', name=op.f('ck_purchase_requisition_items_pri_converted_not_exceed')),
    sa.CheckConstraint('requested_quantity > 0', name=op.f('ck_purchase_requisition_items_pri_qty_positive')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='fk_pri_mat', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pr_id'], ['purchase_requisitions.id'], name='fk_pri_pr', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_requisition_items')),
    sa.UniqueConstraint('pr_id', 'line_no', name='uk_pri_line')
    )
    op.create_index('ix_pri_mat', 'purchase_requisition_items', ['material_id'], unique=False)
    op.create_index('ix_pri_pr', 'purchase_requisition_items', ['pr_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('po_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False, comment='行号'),
    sa.Column('material_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('ordered_quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='采购数量'),
    sa.Column('received_quantity', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False, comment='累计已收数量'),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False, comment='采购单价（confirm 时强制 > 0）'),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), sa.Computed('ROUND(ordered_quantity * unit_price, 4)', persisted=True), nullable=False, comment='金额（生成列）'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Created at (UTC)'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Last updated at (UTC)'),
    sa.CheckConstraint('ordered_quantity > 0', name=op.f('ck_purchase_order_items_poi_ordered_positive')),
    sa.CheckConstraint('received_quantity >= 0 AND received_quantity <= ordered_quantity', name=op.f('ck_purchase_order_items_poi_received_not_exceed')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_purchase_order_items_poi_price_nonneg')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='fk_poi_mat', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name='fk_poi_po', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_items')),
    sa.UniqueConstraint('po_id', 'line_no', name='uk_poi_line')
    )
    op.create_index('ix_poi_mat', 'purchase_order_items', ['material_id'], unique=False)
    op.create_index('ix_poi_po', 'purchase_order_items', ['po_id'], unique=False)
    op.create_table('purchase_receipts',
    sa.Column('receipt_no', sa.String(length=32), nullable=False, comment='REC-20260901-0001'),
    sa.Column('po_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('warehouse_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('received_by', mysql.BIGINT(unsigned=True), nullable=False, comment='收货人'),
    sa.Column('received_at', mysql.DATETIME(fsp=3), nullable=False, comment='收货时间'),
    sa.Column('status', sa.Enum('POSTED', 'REVERSED', name='receiptstatus'), server_default='POSTED', nullable=False),
    sa.Column('reversed_by', mysql.BIGINT(unsigned=True), nullable=True, comment='冲销人'),
    sa.Column('reversed_at', mysql.DATETIME(fsp=3), nullable=True, comment='冲销时间'),
    sa.Column('reverse_reason', sa.String(length=500), nullable=True, comment='冲销原因（必填）'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Created at (UTC)'),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='Last updated at (UTC)'),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name='fk_receipt_po', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], name='fk_receipt_user', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], name='fk_receipt_reversed_by_users'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='fk_receipt_wh', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_receipts')),
    sa.UniqueConstraint('receipt_no', name='uk_receipt_no')
    )
    op.create_index('ix_receipt_po', 'purchase_receipts', ['po_id'], unique=False)
    op.create_index('ix_receipt_status', 'purchase_receipts', ['status'], unique=False)
    op.create_index('ix_receipt_wh', 'purchase_receipts', ['warehouse_id'], unique=False)
    op.create_table('purchase_order_item_sources',
    sa.Column('po_item_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('pr_item_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='从该 PR 明细转出的数量'),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_purchase_order_item_sources_pois_qty_positive')),
    sa.ForeignKeyConstraint(['po_item_id'], ['purchase_order_items.id'], name='fk_pois_poi', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pr_item_id'], ['purchase_requisition_items.id'], name='fk_pois_pri', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_item_sources')),
    sa.UniqueConstraint('po_item_id', 'pr_item_id', name='uk_pois')
    )
    op.create_index('ix_pois_pri', 'purchase_order_item_sources', ['pr_item_id'], unique=False)
    op.create_table('purchase_receipt_items',
    sa.Column('receipt_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('po_item_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False, comment='行号'),
    sa.Column('material_id', mysql.BIGINT(unsigned=True), nullable=False, comment='物料（冗余自 PO 明细，便于库存记账）'),
    sa.Column('received_quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='本次入库数量'),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False, comment='成本单价快照（取自 po_item.unit_price）'),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), sa.Computed('ROUND(received_quantity * unit_price, 4)', persisted=True), nullable=False, comment='入库金额（生成列）'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False, comment='Primary key'),
    sa.CheckConstraint('received_quantity > 0', name=op.f('ck_purchase_receipt_items_ri_qty_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_purchase_receipt_items_ri_price_nonneg')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='fk_ri_mat', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['po_item_id'], ['purchase_order_items.id'], name='fk_ri_poi', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['purchase_receipts.id'], name='fk_ri_receipt', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_receipt_items')),
    sa.UniqueConstraint('receipt_id', 'line_no', name='uk_ri_line'),
    sa.UniqueConstraint('receipt_id', 'po_item_id', name='uk_ri_poi')
    )
    op.create_index('ix_ri_mat', 'purchase_receipt_items', ['material_id'], unique=False)
    op.create_index('ix_ri_poi', 'purchase_receipt_items', ['po_item_id'], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Deferred FKs: departments.created_by/updated_by -> users
    # (added after users exists to break the circular dependency)
    # ------------------------------------------------------------------
    op.create_foreign_key(
        'fk_departments_created_by_users', 'departments', 'users', ['created_by'], ['id']
    )
    op.create_foreign_key(
        'fk_departments_updated_by_users', 'departments', 'users', ['updated_by'], ['id']
    )

    # ------------------------------------------------------------------
    # Append-only ledger enforcement (architecture rule 3, docs §5.4)
    # inventory_transactions may never be UPDATEd or DELETEd after creation;
    # errors are corrected with reversal transactions.
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TRIGGER trg_it_no_update BEFORE UPDATE ON inventory_transactions
        FOR EACH ROW
        BEGIN
            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'inventory_transactions is append-only: UPDATE forbidden, use reversal transaction';
        END
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_it_no_delete BEFORE DELETE ON inventory_transactions
        FOR EACH ROW
        BEGIN
            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'inventory_transactions is append-only: DELETE forbidden, use reversal transaction';
        END
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_it_no_update")
    op.execute("DROP TRIGGER IF EXISTS trg_it_no_delete")
    op.drop_index('ix_ri_poi', table_name='purchase_receipt_items')
    op.drop_index('ix_ri_mat', table_name='purchase_receipt_items')
    op.drop_table('purchase_receipt_items')
    op.drop_index('ix_pois_pri', table_name='purchase_order_item_sources')
    op.drop_table('purchase_order_item_sources')
    op.drop_index('ix_receipt_wh', table_name='purchase_receipts')
    op.drop_index('ix_receipt_status', table_name='purchase_receipts')
    op.drop_index('ix_receipt_po', table_name='purchase_receipts')
    op.drop_table('purchase_receipts')
    op.drop_index('ix_poi_po', table_name='purchase_order_items')
    op.drop_index('ix_poi_mat', table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index('ix_pri_pr', table_name='purchase_requisition_items')
    op.drop_index('ix_pri_mat', table_name='purchase_requisition_items')
    op.drop_table('purchase_requisition_items')
    op.drop_index('ix_po_supplier', table_name='purchase_orders')
    op.drop_index('ix_po_status', table_name='purchase_orders')
    op.drop_index('ix_po_date', table_name='purchase_orders')
    op.drop_index('ix_po_buyer', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index('ix_it_wh_mat', table_name='inventory_transactions')
    op.drop_index('ix_it_type', table_name='inventory_transactions')
    op.drop_index('ix_it_time', table_name='inventory_transactions')
    op.drop_index('ix_it_source', table_name='inventory_transactions')
    op.drop_index('ix_it_reversed', table_name='inventory_transactions')
    op.drop_index('ix_it_mat', table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index('ix_invpol_mat', table_name='inventory_policies')
    op.drop_table('inventory_policies')
    op.drop_index('ix_ib_mat', table_name='inventory_balances')
    op.drop_table('inventory_balances')
    op.drop_index('ix_wh_status', table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index('ix_sup_status', table_name='suppliers')
    op.drop_index('ix_sup_name', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('ix_roleperm_perm', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_pr_status', table_name='purchase_requisitions')
    op.drop_index('ix_pr_dept', table_name='purchase_requisitions')
    op.drop_index('ix_pr_date', table_name='purchase_requisitions')
    op.drop_index('ix_pr_applicant', table_name='purchase_requisitions')
    op.drop_table('purchase_requisitions')
    op.drop_index('ix_ol_time', table_name='operation_logs')
    op.drop_index('ix_ol_operator', table_name='operation_logs')
    op.drop_index('ix_ol_doc', table_name='operation_logs')
    op.drop_index('ix_ol_action', table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index('ix_mat_status', table_name='materials')
    op.drop_index('ix_mat_name', table_name='materials')
    op.drop_table('materials')
    op.drop_index('ix_deptmgr_user', table_name='department_managers')
    op.drop_table('department_managers')
    op.drop_index('ix_ar_time', table_name='approval_records')
    op.drop_index('ix_ar_doc', table_name='approval_records')
    op.drop_index('ix_ar_approver', table_name='approval_records')
    op.drop_table('approval_records')
    op.drop_index('ix_user_status', table_name='users')
    op.drop_index('ix_user_role', table_name='users')
    op.drop_index('ix_user_dept', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_role_status', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_perm_module', table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('number_sequences')
    op.drop_index('ix_dept_status', table_name='departments')
    op.drop_index('ix_dept_parent', table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
